#!/usr/bin/env python3
"""
FILL in the description of the script
"""
import argparse


def parse_args(*argument_array):
  parser = argparse.ArgumentParser()
  args = parser.parse_args(*argument_array)
  return args


def main(args):
  print('I received the following arguments:')
  print(args)


if __name__ == '__main__':
  args = parse_args()
  main(args)
